# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171011_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
